### ISSUE TITLE
NPE on Reloading

### ISSUE THREAD

**Issue by firegore** [bergerkiller/SignLink#1]
Hello, i have SignLink on my Server and everytime when i reload my server i get the following error in the console, the failure comes every second:

Could not pass event BLOCK_BREAK to SignLink
java.lang.NullPointerException
        at com.bergerkiller.bukkit.sl.API.Variables.removeLocation(Variables.java:98)
        at com.bergerkiller.bukkit.sl.SLBlockListener.onBlockBreak(SLBlockListener.java:141)
        at org.bukkit.plugin.java.JavaPluginLoader$40.execute(JavaPluginLoader.java:539)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
        at net.minecraft.server.ItemInWorldManager.c(ItemInWorldManager.java:201)
        at net.minecraft.server.ItemInWorldManager.a(ItemInWorldManager.java:165)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:501)
        at net.minecraft.server.Packet14BlockDig.a(SourceFile:43)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:93)
        at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:527)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

Best Regards
Firegore

**Comment by bergerkiller** [comment]
Thanks, another issue with the block listener not getting disabled by Bukkit...
Will remove the 'setting to null' bit when de-initializing.

EDIT

See the 1.15 version on GitHub.
